sudo: false

language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
    include:
        - php: 5.5
          env: dependencies=lowest

before_script:
  - composer install --no-interaction -o
  - if [ "$dependencies" = "lowest" ]; then composer update -o --prefer-lowest; fi;

script:
  - mkdir -p build/logs
  - vendor/bin/console cache:clear --env=prod
  - vendor/bin/console server:start --env=prod
  - vendor/bin/phpunit
  - vendor/bin/behat

after_script:
  - php bin/coveralls.phar -v
