sudo: false

language: php
php:
  - 5.5

before_script:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - npm install canned
  - nohup node ./node_modules/canned/bin/canned -p 5000 tests/canned >/dev/null 2>&1 &
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v
